//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEEMASTER
    {
        
        public int ID { get; set; }
        public int EMPCODE { get; set; }
        public string EMPNAME { get; set; }
        public string DESTINATION { get; set; }
        public string SALARY { get; set; }
    }
}
